rules:
  allowedAccountTypes:
  - savings
  - joint
  deniedAccountTypes:
  - current
  - huf
  prmThreshold: 5000.0
  accountSearchRelation:
    OTH:
      Others: I
    NON:
      Invalid: I
    MIN:
      Minor: I
